#!/usr/bin/env python3
"""
T8 - Deterministic seed/ETL/reset pipeline.

One command rebuilds every T2-T7 pipeline output from raw sources, in
dependency order:

  T2a  build_skills_taxonomy   (raw ESCO CSVs + config)      -> skills.csv
  T2b  build_skill_aliases     (skills.csv + raw ESCO)       -> skill_aliases.csv
  T3   run_extraction (sample) (skills.csv/aliases + raw resumes/jobs)
                                                              -> t3_mentions_sample.json
  T4   run_normalization       (T3 output + raw resume skills)
                                                              -> t4_resolved_skills.csv
  T5   job_ingestion           (raw jobs xlsx + config)      -> jobs.csv (+ QA files)
  T6prep full_job_extraction   (jobs.csv + skills/aliases)   -> job_skill_resolved.csv
  T6   demand_aggregation      (jobs.csv + job_skill_resolved.csv)
                                                              -> skill_demand_history.csv
  T7   course_alignment        (skills/aliases + demand + raw NPTEL CSVs)
                                                              -> courses.csv, course_skills.csv,
                                                                 training_gap.csv
  T7supp manual_courses        (T7 output + skills/aliases)  -> courses.csv, course_skills.csv,
                                                                 training_gap.csv (final, +20)

Design goals (why this exists as one script, not "just rerun the scripts
in order by hand"):
  - FAIL FAST: if a stage's script exits non-zero, or its declared output
    file(s) don't exist / are empty / are missing a minimum row count
    after it "succeeds", the pipeline stops immediately rather than
    letting a later stage silently run against stale or half-written
    input. No stage is started on top of a failed one.
  - --reset: wipes data/processed/ completely before stage 1, so a run is
    a genuine from-scratch rebuild, never an incremental patch over
    whatever files happened to be sitting there (including debug/stray
    files from manual runs - see NOT_REGENERATED note below).
  - DETERMINISM CHECK: after a full run, writes pipeline_manifest.json -
    every output file's row count and a content hash. Running with
    --reset twice in a row and diffing the two manifests is the actual
    proof of "deterministic", not just an assertion in a docstring.
  - Every stage's stdout/stderr is captured to its own log file under
    logs/, in addition to being streamed to the console, so a failure
    mid-pipeline still leaves a full paper trail of what every prior
    stage printed.

NOT regenerated by this pipeline (by design, not oversight):
  - jobs_BEFORE_correction.csv - a one-off debug snapshot from manual T5
    correction work, never a script output. --reset will make it
    disappear, which is correct, not a bug.

USAGE:
  python3 t8_pipeline.py                 # rebuild everything, keep old outputs as fallback if a stage fails before overwriting them
  python3 t8_pipeline.py --reset         # wipe data/processed/ first, then rebuild everything from raw sources
  python3 t8_pipeline.py --reset --from T5_job_ingestion   # resume from a given stage (skip earlier ones) - for iterating on one stage without waiting through T2-T4 every time. NOTE: does not wipe with --reset in this mode (that would delete the earlier stages' outputs you're relying on) - --reset is ignored with a warning if --from is also given.
  python3 t8_pipeline.py --list          # print the stage list and exit
"""

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd

# Portable root: defaults to the folder this script's parent directory (i.e.
# scripts/.. ), so copying/cloning the whole project anywhere just works with
# no setup. Override with NEXUSAI_ROOT if scripts/ and data/ ever live apart.
# Every t2-t7 script resolves the SAME way independently (each is also
# runnable standalone) - keep this line identical if you ever copy it there.
ROOT = Path(os.environ.get("NEXUSAI_ROOT", Path(__file__).resolve().parent.parent))
SCRIPTS = ROOT / "scripts"
PROCESSED = ROOT / "data" / "processed"
RAW = ROOT / "data" / "raw"
CONFIG = ROOT / "config" / "taxonomy_config.json"
LOGS = ROOT / "logs"

PY = sys.executable

STAGES = [
    dict(
        name="T2a_taxonomy",
        cmd=[PY, str(SCRIPTS / "t2_build_skills_taxonomy.py"),
             "--raw-dir", str(RAW / "esco"), "--out-dir", str(PROCESSED), "--config", str(CONFIG)],
        outputs={"skills.csv": 500},
    ),
    dict(
        name="T2b_aliases",
        cmd=[PY, str(SCRIPTS / "t2_build_skill_aliases.py"),
             "--raw-dir", str(RAW / "esco"), "--out-dir", str(PROCESSED), "--config", str(CONFIG)],
        outputs={"skill_aliases.csv": 1000},
    ),
    dict(
        name="T3_extraction_sample",
        cmd=[PY, str(SCRIPTS / "t3_run_extraction.py")],
        outputs={"t3_mentions_sample.json": 0},  # JSON - row-count check skipped, existence only
    ),
    dict(
        name="T4_normalization",
        cmd=[PY, str(SCRIPTS / "t4_run_normalization.py")],
        outputs={"t4_resolved_skills.csv": 100},
    ),
    dict(
        name="T5_job_ingestion",
        cmd=[PY, str(SCRIPTS / "t5_job_ingestion.py")],
        outputs={"jobs.csv": 10000},
    ),
    dict(
        name="T6prep_full_extraction",
        cmd=[PY, str(SCRIPTS / "t6_prep_full_job_extraction.py")],
        outputs={"job_skill_resolved.csv": 1000},
    ),
    dict(
        name="T6_demand_aggregation",
        cmd=[PY, str(SCRIPTS / "t6_demand_aggregation.py")],
        outputs={"skill_demand_history.csv": 100},
    ),
    dict(
        name="T7_course_alignment",
        cmd=[PY, str(SCRIPTS / "t7_course_alignment.py")],
        outputs={"courses.csv": 40, "course_skills.csv": 100, "training_gap.csv": 100},
    ),
    dict(
        name="T7supp_manual_courses",
        cmd=[PY, str(SCRIPTS / "t7_supplement_manual_courses.py")],
        outputs={"courses.csv": 60, "course_skills.csv": 200, "training_gap.csv": 100},
    ),
]
STAGE_NAMES = [s["name"] for s in STAGES]


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def row_count_of(path: Path) -> int:
    if path.suffix != ".csv":
        return -1  # not applicable (e.g. JSON, txt)
    try:
        # csv.reader, not a raw newline count: a raw count over-reports any file
        # with a quoted multi-line text field (jobs.csv job descriptions, a
        # course name with an embedded line break, etc.) - each embedded \n or
        # lone \r inside a quoted field looks like a row boundary to a naive
        # line count but isn't one. Found via user cross-check: manifest said
        # courses.csv=67 rows, pandas said 66 (one quoted field had a \n in
        # it); jobs.csv was overstated by 16,409 "rows" the same way.
        import csv
        with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
            n = sum(1 for _ in csv.reader(f))
        return max(n - 1, 0)  # minus header
    except Exception:
        return -1


def run_stage(stage: dict, log_dir: Path) -> dict:
    name = stage["name"]
    log_path = log_dir / f"{name}.log"
    print(f"\n{'='*78}\n[STAGE] {name}\n{'='*78}")
    t0 = time.time()
    with open(log_path, "w") as logf:
        proc = subprocess.Popen(stage["cmd"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                 text=True, bufsize=1)
        for line in proc.stdout:
            print(line, end="")
            logf.write(line)
        proc.wait()
    elapsed = time.time() - t0

    if proc.returncode != 0:
        print(f"\n[FAIL] {name} exited {proc.returncode} after {elapsed:.1f}s - "
              f"see {log_path} for full output. Pipeline stopped, no later stage was run.")
        sys.exit(1)

    # validate declared outputs
    for fname, min_rows in stage["outputs"].items():
        fpath = PROCESSED / fname
        if not fpath.exists():
            print(f"\n[FAIL] {name} reported success (exit 0) but declared output "
                  f"{fname} does not exist. Pipeline stopped.")
            sys.exit(1)
        if fpath.stat().st_size == 0:
            print(f"\n[FAIL] {name}'s output {fname} exists but is empty (0 bytes). Pipeline stopped.")
            sys.exit(1)
        if min_rows > 0:
            n = row_count_of(fpath)
            if n < min_rows:
                print(f"\n[FAIL] {name}'s output {fname} has {n} data rows, expected >= {min_rows}. "
                      f"Pipeline stopped - this smells like a silent partial-write, not a real result.")
                sys.exit(1)

    print(f"\n[OK] {name} - {elapsed:.1f}s - " +
          ", ".join(f"{f} ({row_count_of(PROCESSED/f)} rows)" if f.endswith(".csv") else f
                     for f in stage["outputs"]))

    # T7supp needs a pre-supplement snapshot of training_gap.csv to report a
    # real before/after delta - take it right after the stage that produces
    # the NPTEL-only baseline, before the supplement stage overwrites it.
    if name == "T7_course_alignment":
        shutil.copy(PROCESSED / "training_gap.csv", PROCESSED / "training_gap_PRE_SUPPLEMENT_BACKUP.csv")

    return dict(stage=name, elapsed_seconds=round(elapsed, 2), returncode=proc.returncode)


def build_manifest() -> dict:
    files = {}
    for f in sorted(PROCESSED.glob("*")):
        if f.is_file():
            files[f.name] = dict(
                bytes=f.stat().st_size,
                sha256=sha256_of(f),
                rows=row_count_of(f) if f.suffix == ".csv" else None,
            )
    return files


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--reset", action="store_true",
                     help="Wipe data/processed/ completely before running (from-scratch rebuild).")
    ap.add_argument("--from", dest="from_stage", default=None, choices=STAGE_NAMES,
                     help="Resume from this stage, skipping earlier ones. Ignores --reset.")
    ap.add_argument("--list", action="store_true", help="Print the stage list and exit.")
    args = ap.parse_args()

    if args.list:
        for i, s in enumerate(STAGES, 1):
            print(f"{i}. {s['name']:28s} -> {', '.join(s['outputs'])}")
        return

    stages_to_run = STAGES
    if args.from_stage:
        if args.reset:
            print("[WARN] --reset ignored: --from resumes mid-pipeline and relies on earlier "
                  "stages' existing outputs, which --reset would delete.")
        idx = STAGE_NAMES.index(args.from_stage)
        stages_to_run = STAGES[idx:]
        print(f"[RESUME] Running from {args.from_stage} onward ({len(stages_to_run)}/{len(STAGES)} stages). "
              f"Earlier stages' outputs are assumed present and unchanged.")
    elif args.reset:
        if (PROCESSED / "skills.csv").exists():
            print("\n" + "!" * 78)
            print("[RESET WARNING] skills.csv already exists. T2's ID-stability mechanism ONLY")
            print("carries skill_id forward when a PREVIOUS skills.csv is present for it to read.")
            print("--reset deletes that file BEFORE T2 runs, so this rebuild has nothing to carry")
            print("forward from and will mint a FRESH skill_id numbering for all ~642 skills -")
            print("internally self-consistent, but DIFFERENT from the numbering that exists right")
            print("now. If Member 3's DB, or anything else, has already ingested specific SKILL_")
            print("XXXX values from the current files, those references break silently.")
            print("Safe once real consumers depend on specific IDs: rerun WITHOUT --reset (T2")
            print("then carries every existing ID forward unchanged), or use --from to resume")
            print("mid-pipeline. Reserve --reset for pre-handoff dev iteration only.")
            print("!" * 78)
        if PROCESSED.exists():
            n_before = len(list(PROCESSED.glob("*")))
            shutil.rmtree(PROCESSED)
            print(f"\n[RESET] Deleted {n_before} file(s) from {PROCESSED}")
        PROCESSED.mkdir(parents=True, exist_ok=True)

    run_id = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    log_dir = LOGS / f"t8_run_{run_id}"
    log_dir.mkdir(parents=True, exist_ok=True)
    print(f"[T8] Run {run_id} - {len(stages_to_run)} stage(s) - logs: {log_dir}")

    t_start = time.time()
    stage_results = [run_stage(s, log_dir) for s in stages_to_run]
    total_elapsed = time.time() - t_start

    manifest = dict(
        run_id=run_id,
        reset=bool(args.reset and not args.from_stage),
        from_stage=args.from_stage,
        total_elapsed_seconds=round(total_elapsed, 2),
        stages=stage_results,
        files=build_manifest(),
    )
    manifest_path = PROCESSED / "pipeline_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))

    print(f"\n{'='*78}\n[T8 COMPLETE] {len(stages_to_run)} stages, {total_elapsed:.1f}s total")
    print(f"Manifest written to {manifest_path} ({len(manifest['files'])} files fingerprinted).")
    print("Compare two --reset runs' manifests (files.*.sha256 / .rows) to verify determinism.")


if __name__ == "__main__":
    main()
